from __future__ import annotations

import os
import re
import subprocess
from importlib.machinery import EXTENSION_SUFFIXES
from pathlib import Path

import torch
from pybind11.setup_helpers import Pybind11Extension
from setuptools import find_packages, setup
from torch.utils.cpp_extension import (
    CUDA_HOME,
    BuildExtension,
    CppExtension,
    CUDAExtension,
)

cuda_option = os.environ.get("BUILD_CUDA", "1")
if cuda_option not in ("0", "1"):
    raise RuntimeError("BUILD_CUDA must be '0' or '1'")
build_with_cuda = cuda_option == "1"

extensions = [
    Pybind11Extension(
        name="tonari._numpy_cpu",
        sources=[
            "csrc/numpy/bindings.cpp",
            "csrc/core/geometry.cpp",
            "csrc/core/neighbors_cpu.cpp",
            "csrc/core/thread_pool.cpp",
        ],
        depends=[
            "csrc/core/algorithm.h",
            "csrc/core/errors.h",
            "csrc/core/geometry.h",
            "csrc/core/neighbors_cpu.h",
            "csrc/core/pair_policy.h",
            "csrc/core/thread_pool.h",
        ],
        cxx_std=20,
        extra_compile_args=["-O3", "-pthread"],
        extra_link_args=["-pthread"],
    ),
    CppExtension(
        name="tonari._torch_cpu",
        sources=[
            "csrc/torch/bindings_cpu.cpp",
            "csrc/core/geometry.cpp",
            "csrc/core/neighbors_cpu.cpp",
            "csrc/core/thread_pool.cpp",
        ],
        depends=[
            "csrc/core/algorithm.h",
            "csrc/core/errors.h",
            "csrc/core/geometry.h",
            "csrc/core/neighbors_cpu.h",
            "csrc/core/pair_policy.h",
            "csrc/core/thread_pool.h",
        ],
        extra_compile_args=["-O3", "-pthread"],
        extra_link_args=["-pthread"],
    ),
]

cuda_toolkit_version = None
if build_with_cuda:
    if torch.version.cuda is None:
        raise RuntimeError(
            "the default CUDA build requires a CUDA-enabled PyTorch installation; "
            "set BUILD_CUDA=0 for a CPU-only build"
        )
    if CUDA_HOME is None:
        raise RuntimeError(
            "the default CUDA build requires a CUDA toolkit containing nvcc; "
            "set BUILD_CUDA=0 for a CPU-only build"
        )

    nvcc = Path(CUDA_HOME) / "bin" / "nvcc"
    try:
        nvcc_output = subprocess.run(
            [str(nvcc), "--version"],
            check=True,
            capture_output=True,
            text=True,
        ).stdout
    except (OSError, subprocess.CalledProcessError) as error:
        raise RuntimeError(f"failed to query the CUDA compiler at {nvcc}") from error
    match = re.search(r"release\s+([0-9]+(?:\.[0-9]+)?)", nvcc_output)
    if match is None:
        raise RuntimeError("could not determine the CUDA toolkit version from nvcc")
    cuda_toolkit_version = match.group(1)

    extensions.append(
        CUDAExtension(
            name="tonari._torch_cuda",
            sources=[
                "csrc/torch/bindings_cuda.cpp",
                "csrc/core/geometry.cpp",
                "csrc/torch/neighbors_cuda.cu",
                "csrc/torch/neighbors_cell_cuda.cu",
            ],
            depends=[
                "csrc/core/algorithm.h",
                "csrc/core/errors.h",
                "csrc/core/geometry.h",
                "csrc/core/pair_policy.h",
                "csrc/torch/neighbors_cuda.h",
            ],
            extra_compile_args={
                "cxx": ["-O3"],
                "nvcc": ["-O3", "-lineinfo"],
            },
        )
    )


class TonariBuildExt(BuildExtension.with_options(use_ninja=True)):
    def run(self) -> None:
        super().run()
        package_dir = Path(self.get_ext_fullpath("tonari._numpy_cpu")).parent
        package_dir.mkdir(parents=True, exist_ok=True)
        if not build_with_cuda:
            for suffix in EXTENSION_SUFFIXES:
                stale_extension = package_dir / f"_torch_cuda{suffix}"
                if stale_extension.exists():
                    stale_extension.unlink()
        content = (
            "# Generated by the tonari build; do not edit.\n"
            f"BUILD_WITH_CUDA = {build_with_cuda!r}\n"
            f"BUILD_TORCH_VERSION = {torch.__version__!r}\n"
            f"BUILD_TORCH_CUDA_VERSION = {torch.version.cuda!r}\n"
            f"BUILD_CUDA_TOOLKIT_VERSION = {cuda_toolkit_version!r}\n"
        )
        (package_dir / "_build_info.py").write_text(content, encoding="utf-8")


setup(
    packages=find_packages("src"),
    package_dir={"": "src"},
    ext_modules=extensions,
    cmdclass={"build_ext": TonariBuildExt},
)
